# Generated by Django 5.2.3 on 2026-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('beard', 'Beard'), ('haircut', 'Haircut')], max_length=50)),
            ],
        ),
    ]
