# Generated by Django 5.2.3 on 2026-01-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
