# Generated by Django 5.2.7 on 2026-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_delete_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="lookbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
